timeout: 10m
format: table
dependency-tree: true
list-all-pkgs: true
exit-code: 1
quiet: true
severity:
  - MEDIUM
  - HIGH
  - CRITICAL
scan:
  scanners:
    - misconfig
    - secret
    - vuln
pkg:
  type:
    - os
    - library
  ignore-unfixed: true
